version: "3.7"

services:
    app:
        build:
            context: ./
            dockerfile: docker/app/Dockerfile
        image: coaching-platform-app
        container_name: coaching-platform-app
        restart: unless-stopped
        working_dir: /var/www/
        ports:
            - 5173:5173
        depends_on:
            - db
        volumes:
            - ./:/var/www
        networks:
            - coaching-platform

    db:
        image: mysql:5.7
        platform: linux/x86_64
        container_name: coaching-platform-db
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
            interval: 10s
            retries: 3
            timeout: 5s
        networks:
            - coaching-platform
        volumes:
            - coaching-platform:/var/lib/mysql

    nginx:
        image: nginx:alpine
        container_name: coaching-platform-nginx
        restart: unless-stopped
        ports:
            - "80:80"
        depends_on:
            - app
        volumes:
            - ./:/var/www
            - ./docker/nginx/${NGINX_CONF_NAME}:/etc/nginx/conf.d/default.conf
        networks:
            - coaching-platform

    redis:
        image: redis:7
        container_name: coaching-platform-redis
        ports:
            - "6379:6379"
        networks:
            - coaching-platform
        command:
            redis-server --appendonly yes --replica-read-only no

    elasticsearch:
        image: elasticsearch:8.2.2
        container_name: coaching-platform-elasticsearch
        environment:
            - discovery.type=single-node
            - ES_JAVA_OPTS=-Xms1g -Xmx1g
            - xpack.security.enabled=${ELASTICSEARCH_SECURITY_ENABLED}
            - ELASTIC_PASSWORD=${ELASTICSEARCH_PASSWORD}
            - action.destructive_requires_name=false
        ports:
            - "9200:9200"
        networks:
            - coaching-platform

volumes:
    coaching-platform:

networks:
    coaching-platform:
        driver: bridge
